// Database Kartu Karakter Anime untuk Sistem Gacha Holographic 3D & Auto-Battle Arena
export const RARITY_CONFIG = {
  UR: {
    label: 'Ultra Rare (Mythic)',
    short: 'UR',
    rate: 1.5, // 1.5%
    color: '#ff2a70',
    border: 'border-[#ff2a70]',
    glow: 'rgba(255, 42, 112, 0.6)',
    bgGradient: 'from-[#ff2a70]/30 via-[#7928ca]/20 to-[#00dfd8]/30',
    holoClass: 'holo-ur',
    stars: 5,
    badgeBg: 'bg-gradient-to-r from-pink-500 via-purple-500 to-cyan-400 text-white shadow-lg shadow-pink-500/30'
  },
  SSR: {
    label: 'Special Super Rare',
    short: 'SSR',
    rate: 6.5, // 6.5%
    color: '#f59e0b',
    border: 'border-[#f59e0b]',
    glow: 'rgba(245, 158, 11, 0.5)',
    bgGradient: 'from-[#f59e0b]/30 via-[#d97706]/20 to-[#78350f]/30',
    holoClass: 'holo-ssr',
    stars: 4,
    badgeBg: 'bg-gradient-to-r from-amber-400 to-yellow-500 text-black font-black shadow-lg shadow-amber-500/30'
  },
  SR: {
    label: 'Super Rare',
    short: 'SR',
    rate: 22.0, // 22%
    color: '#a855f7',
    border: 'border-[#a855f7]',
    glow: 'rgba(168, 85, 247, 0.4)',
    bgGradient: 'from-[#a855f7]/25 via-[#6b21a8]/15 to-[#3b0764]/25',
    holoClass: 'holo-sr',
    stars: 3,
    badgeBg: 'bg-gradient-to-r from-purple-500 to-indigo-600 text-white font-black shadow-lg shadow-purple-500/25'
  },
  R: {
    label: 'Rare',
    short: 'R',
    rate: 40.0, // 40%
    color: '#06b6d4',
    border: 'border-[#06b6d4]',
    glow: 'rgba(6, 182, 212, 0.35)',
    bgGradient: 'from-[#06b6d4]/20 via-[#0e7490]/15 to-[#164e63]/20',
    holoClass: 'holo-r',
    stars: 2,
    badgeBg: 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 font-bold'
  },
  C: {
    label: 'Common',
    short: 'C',
    rate: 30.0, // 30%
    color: '#94a3b8',
    border: 'border-[#94a3b8]',
    glow: 'rgba(148, 163, 184, 0.2)',
    bgGradient: 'from-slate-700/20 via-slate-800/10 to-slate-900/20',
    holoClass: '',
    stars: 1,
    badgeBg: 'bg-white/10 text-white/70 border border-white/10 font-medium'
  }
};

// Elemen kartu menggunakan nama icon Lucide (bukan emoji)
export const ELEMENTS = {
  Void: { name: 'Void', color: '#a855f7', iconName: 'Orbit' },
  Light: { name: 'Light', color: '#fbbf24', iconName: 'Sun' },
  Shadow: { name: 'Shadow', color: '#6366f1', iconName: 'Moon' },
  Chaos: { name: 'Chaos', color: '#ef4444', iconName: 'Zap' },
  Earth: { name: 'Earth', color: '#84cc16', iconName: 'Globe' },
  Holy: { name: 'Holy', color: '#38bdf8', iconName: 'ShieldCheck' },
  Flame: { name: 'Flame', color: '#f97316', iconName: 'Flame' },
  Wind: { name: 'Wind', color: '#10b981', iconName: 'Wind' },
  Lightning: { name: 'Lightning', color: '#eab308', iconName: 'Zap' },
  Dark: { name: 'Dark', color: '#8b5cf6', iconName: 'EyeOff' },
  Blood: { name: 'Blood', color: '#dc2626', iconName: 'Droplets' },
  Arcane: { name: 'Arcane', color: '#c084fc', iconName: 'Wand2' },
  Mind: { name: 'Mind', color: '#ec4899', iconName: 'Brain' },
  Sound: { name: 'Sound', color: '#f43f5e', iconName: 'Music' },
  Secret: { name: 'Secret', color: '#64748b', iconName: 'KeyRound' },
  Beast: { name: 'Beast', color: '#d97706', iconName: 'Skull' },
  Poison: { name: 'Poison', color: '#e11d48', iconName: 'FlaskConical' },
  Luck: { name: 'Luck', color: '#eab308', iconName: 'Crown' },
  Water: { name: 'Water', color: '#0ea5e9', iconName: 'Waves' },
  Steel: { name: 'Steel', color: '#cbd5e1', iconName: 'Sword' }
};

export const CARDS_DATABASE = [
  // ===== 1. ULTRA RARE (UR) =====
  {
    id: 'gojo_void',
    name: 'Gojo Satoru',
    subtitle: 'Limitless Void & Hollow Purple',
    anime: 'Jujutsu Kaisen',
    rarity: 'UR',
    element: 'Void',
    atk: 9999,
    def: 9999,
    hp: 25000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b127691-9zqh1xpIubn7.png',
    quote: 'Daijoubu, boku saikyou dakara. (Ryoiki Tenkai: Muryoukuusho!)',
    description: 'Penyihir Jujutsu terkuat era modern. Menguasai Limitless dan Six Eyes yang membuatnya tak tersentuh oleh serangan apa pun.',
    featured: true
  },
  {
    id: 'luffy_gear5',
    name: 'Monkey D. Luffy',
    subtitle: 'Warrior of Liberation (Gear 5)',
    anime: 'One Piece',
    rarity: 'UR',
    element: 'Light',
    atk: 9800,
    def: 9200,
    hp: 24500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b40-MNypXsxSRb1R.png',
    quote: 'Kore ga ore no saikou chiten da! Ini titik puncak kekuatanku... GEAR 5!',
    description: 'Awakening dari Hito Hito no Mi Model: Nika, Dewa Matahari yang membawa tawa dan kebebasan ke seluruh samudra.',
    featured: true
  },
  {
    id: 'sung_jinwoo',
    name: 'Sung Jin-Woo',
    subtitle: 'Shadow Monarch (Arise)',
    anime: 'Solo Leveling',
    rarity: 'UR',
    element: 'Shadow',
    atk: 9950,
    def: 9400,
    hp: 25500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b129928-BCEjVaP0AQSw.png',
    quote: 'Ilonala. (Bangkitlah!)',
    description: 'Raja Bayangan yang mengomandoi jutaan prajurit abadi. Tidak ada kematian di hadapan sang Shadow Monarch.',
    featured: true
  },
  {
    id: 'saitama_punch',
    name: 'Saitama',
    subtitle: 'One Punch Man (Serious Series)',
    anime: 'One Punch Man',
    rarity: 'UR',
    element: 'Void',
    atk: 10500,
    def: 10000,
    hp: 26000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b73935-ON5d0mAcrItd.jpg',
    quote: 'Hissatsu: Maji Naguri! (Pukulan Serius!)',
    description: 'Pria yang menjadi pahlawan hanya untuk hobi, dengan kekuatan fisik tak terbatas yang mampu menghancurkan bintang.',
    featured: true
  },
  {
    id: 'sasuke_rinnegan',
    name: 'Sasuke Uchiha',
    subtitle: 'Indra Reincarnation (Rinnegan & Susanoo)',
    anime: 'Naruto Shippuden',
    rarity: 'UR',
    element: 'Lightning',
    atk: 9750,
    def: 9300,
    hp: 24000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b13-SISLEw1oAD7a.png',
    quote: 'Indra no Ya! (Panah Indra!)',
    description: 'Pemilik Eternal Mangekyou Sharingan dan Rinnegan berkekuatan Ruang & Waktu Amenotejikara.',
    featured: true
  },
  {
    id: 'madara_sixpaths',
    name: 'Madara Uchiha',
    subtitle: 'Ghost of the Uchiha (Ten-Tails Jinchuriki)',
    anime: 'Naruto Shippuden',
    rarity: 'UR',
    element: 'Chaos',
    atk: 9900,
    def: 9600,
    hp: 25000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b53901-HnRKSoHMG5Vg.png',
    quote: 'Apakah kalian ingin klon ini menggunakan Susanoo juga atau tidak?',
    description: 'Legenda klan Uchiha yang membangkitkan Mugen Tsukuyomi dan menguasai Rinnegan kedua bola mata.',
    featured: false
  },
  {
    id: 'sukuna_curse',
    name: 'Ryomen Sukuna',
    subtitle: 'King of Curses (20 Fingers Reborn)',
    anime: 'Jujutsu Kaisen',
    rarity: 'UR',
    element: 'Chaos',
    atk: 10200,
    def: 9500,
    hp: 25500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b133701-rCQuDpHr3UZL.png',
    quote: 'Fukuma Mizushi. Ketahuilah tempatmu berdiri di hadapanku.',
    description: 'Raja Kutukan dari zaman Heian. Menguasai Dismantle, Cleave, dan Domain Expansion tanpa batas penghalang.',
    featured: false
  },
  {
    id: 'eren_founding',
    name: 'Eren Yeager',
    subtitle: 'The Founding Titan (The Rumbling)',
    anime: 'Attack on Titan',
    rarity: 'UR',
    element: 'Earth',
    atk: 9600,
    def: 9600,
    hp: 26000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b40882-dsj7IP943WFF.jpg',
    quote: 'Tatakae... Tatakae! Kalau kita tidak bertarung, kita tidak bisa menang!',
    description: 'Pewaris Founding, Attack, dan War Hammer Titan yang memicu The Rumbling demi kebebasan pulau Paradis.',
    featured: false
  },
  {
    id: 'toji_zenin',
    name: 'Toji Fushiguro',
    subtitle: 'Sorcerer Killer (Heavenly Restriction)',
    anime: 'Jujutsu Kaisen',
    rarity: 'UR',
    element: 'Steel',
    atk: 9850,
    def: 9500,
    hp: 24500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b162722-btzdghBizxKS.jpg',
    quote: 'Kalian penyihir yang diberkati energi terkutuk... kalah oleh monyet tanpa kutukan seperti diriku.',
    description: 'Manusia dengan Heavenly Restriction mutlak. Kecepatan, panca indera, dan refleks fisiknya melampaui puncak penyihir kelas spesial.',
    featured: false
  },
  {
    id: 'yuta_rika',
    name: 'Yuta Okkotsu',
    subtitle: 'Special Grade Sorcerer & Rika',
    anime: 'Jujutsu Kaisen',
    rarity: 'UR',
    element: 'Void',
    atk: 9700,
    def: 9400,
    hp: 25000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b129571-GHJk7gviHOOw.jpg',
    quote: 'Kore wa jun\'ai da yo. (Ini adalah cinta sejati.) Rika-chan, pinjamkan kekuatanmu!',
    description: 'Penyihir Jujutsu keturunan Sugawara no Michizane dengan cadangan energi kutukan tak terbatas dan kemampuan meniru teknik.',
    featured: false
  },

  // ===== 2. SPECIAL SUPER RARE (SSR) =====
  {
    id: 'frieren_magic',
    name: 'Frieren',
    subtitle: 'Mage of the Funeral',
    anime: 'Sousou no Frieren',
    rarity: 'SSR',
    element: 'Arcane',
    atk: 8800,
    def: 8200,
    hp: 21000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b176754-PCnpqIOkjhFk.png',
    quote: 'Zoltraak. Sihir yang mengalahkan iblis.',
    description: 'Penyihir Elf berumur lebih dari seribu tahun yang telah mempelajari ribuan jenis sihir dan memusnahkan pasukan raja iblis.',
    featured: true
  },
  {
    id: 'naruto_baryon',
    name: 'Naruto Uzumaki',
    subtitle: 'Seventh Hokage (Kurama Link)',
    anime: 'Naruto Shippuden',
    rarity: 'SSR',
    element: 'Flame',
    atk: 8900,
    def: 8300,
    hp: 22000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b17-phjcWCkRuIhu.png',
    quote: 'Ore ga akirameru no wo, akiramero! (Menyerahlah untuk membuatku menyerah!)',
    description: 'Pahlawan Konoha yang mewujudkan ikatan perdamaian dunia shinobi dengan tekad baja Rasengan dan Chakra Ekor Sembilan.',
    featured: false
  },
  {
    id: 'itachi_tsukuyomi',
    name: 'Itachi Uchiha',
    subtitle: 'Shadow of the Leaf (Mangekyou Sharingan)',
    anime: 'Naruto Shippuden',
    rarity: 'SSR',
    element: 'Flame',
    atk: 8850,
    def: 8250,
    hp: 21500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b14-9Kb1E5oel1ke.png',
    quote: 'Tsukuyomi. Di dalam duniaku, ruang, waktu, dan massa berada di bawah kendaliku sepenuhnya.',
    description: 'Shinobi jenius pelindung Konoha dari balik bayang-bayang. Menguasai Amaterasu api hitam abadi dan ilusi Tsukuyomi.',
    featured: false
  },
  {
    id: 'rengoku_flame',
    name: 'Kyojuro Rengoku',
    subtitle: 'Flame Hashira (Ninth Form: Rengoku)',
    anime: 'Kimetsu no Yaiba',
    rarity: 'SSR',
    element: 'Flame',
    atk: 8950,
    def: 7900,
    hp: 21000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b129133-VlTPowwt68rJ.png',
    quote: 'Bakar hatimu! Lampaui batasmu! Setto wo moyase!',
    description: 'Pilar Api yang pantang menyerah. Menghadapi Iblis Bulan Atas demi melindungi seluruh penumpang Kereta Mugen.',
    featured: false
  },
  {
    id: 'giyu_water',
    name: 'Giyu Tomioka',
    subtitle: 'Water Hashira (Eleventh Form: Dead Calm)',
    anime: 'Kimetsu no Yaiba',
    rarity: 'SSR',
    element: 'Water',
    atk: 8500,
    def: 8700,
    hp: 21500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b130050-qsLThJs5VIbz.png',
    quote: 'Mizu no Kokyuu, Juichi no Kata: Nagi. (Pernapasan Air Bentuk Kesebelas: Ketenangan Mutlak.)',
    description: 'Pilar Air pencipta jurus Ketenangan Mutlak yang mampu menepis segala serangan musuh tanpa cela.',
    featured: false
  },
  {
    id: 'kurapika_emperor',
    name: 'Kurapika',
    subtitle: 'Last Survivor of Kurta (Emperor Time)',
    anime: 'Hunter x Hunter',
    rarity: 'SSR',
    element: 'Holy',
    atk: 8800,
    def: 8400,
    hp: 21000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b28-ivA7UGnfE40a.png',
    quote: 'Emperor Time! Saat mataku berubah merah darah, aku menguasai seluruh rumpun Nen 100%!',
    description: 'Anggota terakhir klan Kurta yang memburu Phantom Troupe dengan rantai Nen pengikat sumpah mematikan.',
    featured: false
  },
  {
    id: 'edward_elric',
    name: 'Edward Elric',
    subtitle: 'The Fullmetal Alchemist',
    anime: 'Fullmetal Alchemist: Brotherhood',
    rarity: 'SSR',
    element: 'Earth',
    atk: 8600,
    def: 8500,
    hp: 21500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b11-TA5Nuk7EDUZG.jpg',
    quote: 'Hukum Pertukaran Setara: Manusia tak dapat memperoleh apa pun tanpa mengorbankan sesuatu!',
    description: 'Alkemis termuda dalam sejarah militer Amestris yang mampu melakukan transmutasi alkimia tanpa lingkaran sihir.',
    featured: false
  },
  {
    id: 'roy_mustang',
    name: 'Roy Mustang',
    subtitle: 'The Flame Alchemist',
    anime: 'Fullmetal Alchemist: Brotherhood',
    rarity: 'SSR',
    element: 'Flame',
    atk: 8900,
    def: 8000,
    hp: 20500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b68-moBLY2WO2am3.png',
    quote: '*Jentikan jari* Ledakan api presisi tinggi ini akan membakar habis seluruh sel regenerasimu!',
    description: 'Kolonel militer Amestris bersarung tangan kain pengapian yang memicu gelombang ledakan api berdaya hancur masif.',
    featured: false
  },
  {
    id: 'mob_kageyama',
    name: 'Kageyama Shigeo (Mob)',
    subtitle: 'Esper Explosion 100% / ???%',
    anime: 'Mob Psycho 100',
    rarity: 'SSR',
    element: 'Mind',
    atk: 8950,
    def: 8350,
    hp: 22000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b89616-dXmdOc7L6SDi.png',
    quote: 'Ketika emosiku mencapai 100%, tak ada yang bisa menghentikan ledakan psikis ini.',
    description: 'Remaja polos yang menyimpan energi psikokinesis penghancur kosmik ketika batas toleransi emosinya meledak 100%.',
    featured: false
  },
  {
    id: 'rimuru_tempest',
    name: 'Rimuru Tempest',
    subtitle: 'Demon Lord & Great Sage',
    anime: 'Tensei shitara Slime Datta Ken',
    rarity: 'SSR',
    element: 'Chaos',
    atk: 8750,
    def: 8500,
    hp: 21500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b123962-eL9yGV0NLMF7.png',
    quote: 'Aku cuma slime biasa yang kebetulan jadi Raja Iblis!',
    description: 'Pemimpin Federasi Jura Tempest yang menguasai Ultimate Skill Raphael dan Beelzebuth penelan segalanya.',
    featured: false
  },
  {
    id: 'ichigo_bankai',
    name: 'Ichigo Kurosaki',
    subtitle: 'Substitute Shinigami (Getsuga Tenshou)',
    anime: 'Bleach: Thousand-Year Blood War',
    rarity: 'SSR',
    element: 'Shadow',
    atk: 8900,
    def: 8100,
    hp: 21000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b5-a7bkJgjhhigE.png',
    quote: 'Bankai! Tensa Zangetsu!! Getsuga... JUJISHO!',
    description: 'Penyatu darah Shinigami, Hollow, dan Quincy yang menguasai Zangetsu ganda demi melindungi teman-temannya.',
    featured: false
  },
  {
    id: 'kaneki_kakuja',
    name: 'Ken Kaneki',
    subtitle: 'One-Eyed Ghoul (Centipede Kakuja)',
    anime: 'Tokyo Ghoul',
    rarity: 'SSR',
    element: 'Dark',
    atk: 8850,
    def: 8150,
    hp: 21500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b87275-mb13EWZBdbh3.png',
    quote: '1000 dikurang 7 itu berapa? Beritahu aku!',
    description: 'Ghoul bermata satu berambut putih yang menerima sisi monsternya dan menguasai Kagune Rinkaku mengerikan.',
    featured: false
  },
  {
    id: 'tanjiro_sun',
    name: 'Tanjiro Kamado',
    subtitle: 'Sun Breathing (Hinokami Kagura)',
    anime: 'Kimetsu no Yaiba',
    rarity: 'SSR',
    element: 'Flame',
    atk: 8700,
    def: 8400,
    hp: 22000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b126071-BTNEc1nRIv68.png',
    quote: 'Hinokami Kagura: Enbu! Terus maju pantang mundur!',
    description: 'Pemburu iblis berpedang hitam nichirin yang membangkitkan Pernapasan Matahari legendaris demi menyembuhkan Nezuko.',
    featured: false
  },
  {
    id: 'zoro_kingofhell',
    name: 'Roronoa Zoro',
    subtitle: 'King of Hell (Three Sword Style)',
    anime: 'One Piece',
    rarity: 'SSR',
    element: 'Wind',
    atk: 8950,
    def: 8050,
    hp: 21500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b62-S7oAeA9WInjV.png',
    quote: 'Aku akan menjadi Raja Neraka demi kaptenku! Santoryu Ougi: Sanzen Sekai!',
    description: 'Pendekar Tiga Pedang bertaraf Conqueror Haki yang menguasai Enma dan berjanji takkan pernah kalah lagi.',
    featured: false
  },

  // ===== 3. SUPER RARE (SR) =====
  {
    id: 'killua_godspeed',
    name: 'Killua Zoldyck',
    subtitle: 'Lightning Assassin (Godspeed)',
    anime: 'Hunter x Hunter',
    rarity: 'SR',
    element: 'Lightning',
    atk: 7800,
    def: 6900,
    hp: 17000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b27-Z5O02kQUydpT.jpg',
    quote: 'Kanmuru! Kecepatan kilat ini melampaui saraf otak manusia!',
    description: 'Pewaris keluarga pembunuh bayaran Zoldyck yang memanipulasi aura listrik ke seluruh aliran saraf tubuhnya.',
    featured: false
  },
  {
    id: 'levi_ackerman',
    name: 'Levi Ackerman',
    subtitle: 'Humanity\'s Strongest Soldier',
    anime: 'Attack on Titan',
    rarity: 'SR',
    element: 'Wind',
    atk: 7900,
    def: 6800,
    hp: 16500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b45627-CR68RyZmddGG.png',
    quote: 'Pilihlah keputusan yang paling tidak akan kau sesali nantinya.',
    description: 'Kapten Pasukan Pengintai yang membantai puluhan Titan dalam sekejap mata dengan manuver 3D Gear kecepatan tinggi.',
    featured: false
  },
  {
    id: 'shinobu_kocho',
    name: 'Shinobu Kocho',
    subtitle: 'Insect Hashira (Wisteria Poison Dance)',
    anime: 'Kimetsu no Yaiba',
    rarity: 'SR',
    element: 'Poison',
    atk: 7600,
    def: 6700,
    hp: 16000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b136070-MC9LLxJsHyHE.png',
    quote: 'Mushi no Kokyuu: Chou no Mai: Tawamure! (Tarian Kupu-kupu Beracun!)',
    description: 'Pilar Serangga yang menggunakan racun bunga wisteria mematikan untuk membasmi iblis.',
    featured: false
  },
  {
    id: 'stark_frieren',
    name: 'Stark',
    subtitle: 'Warrior of Eisen\'s Lineage',
    anime: 'Sousou no Frieren',
    rarity: 'SR',
    element: 'Steel',
    atk: 7700,
    def: 7200,
    hp: 18000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b184313-CQl6GSt4RSny.jpg',
    quote: 'Aku memang penakut, tapi tubuhku bergerak untuk melindungi mereka!',
    description: 'Pendekar kapak murid Eisen yang memiliki ketahanan fisik raksasa dan mampu membelah tebing dalam satu tebasan.',
    featured: false
  },
  {
    id: 'fern_frieren',
    name: 'Fern',
    subtitle: 'First-Class Prodigy Mage',
    anime: 'Sousou no Frieren',
    rarity: 'SR',
    element: 'Arcane',
    atk: 7750,
    def: 6950,
    hp: 16500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b183965-uGFohBjlFoTp.png',
    quote: 'Menembakkan Zoltraak dengan kecepatan tinggi dan konsisten adalah kunci kemenangan.',
    description: 'Penyihir Kelas Satu murid Frieren yang menguasai serangan sihir Zoltraak tercepat tanpa celah waktu cast.',
    featured: false
  },
  {
    id: 'maomao_apothecary',
    name: 'Maomao',
    subtitle: 'Poison-Tasting Apothecary',
    anime: 'Kusuriya no Hitorigoto',
    rarity: 'SR',
    element: 'Poison',
    atk: 7100,
    def: 7300,
    hp: 17500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b126824-MqsCncTO1qpv.png',
    quote: 'Ini bukan sekadar racun biasa... ini adalah racun yang sangat lezat!',
    description: 'Gadis apoteker cerdas yang memiliki kekebalan alami terhadap berbagai jenis racun mematikan.',
    featured: false
  },
  {
    id: 'jinshi_strategist',
    name: 'Jinshi',
    subtitle: 'Imperial Court Overseer',
    anime: 'Kusuriya no Hitorigoto',
    rarity: 'SR',
    element: 'Mind',
    atk: 7300,
    def: 7100,
    hp: 17000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b127278-0qCQciTkPOMS.jpg',
    quote: 'Pesona dan siasat istana ini bergerak di bawah pengawasanku.',
    description: 'Pejabat tinggi istana berparas rupawan luar biasa yang mengendalikan intrik dan strategi kekaisaran.',
    featured: false
  },
  {
    id: 'thorfinn_dagger',
    name: 'Thorfinn Karlsefni',
    subtitle: 'Dual Dagger Berserker',
    anime: 'Vinland Saga',
    rarity: 'SR',
    element: 'Wind',
    atk: 7850,
    def: 6600,
    hp: 16500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b10138-zOPrka0ddZOR.png',
    quote: 'Aku tidak punya musuh. Tak ada seorang pun di dunia ini yang pantas disakiti.',
    description: 'Prajurit Viking lincah berpisau ganda yang bertransformasi mencari tanah damai tanpa perbudakan.',
    featured: false
  },
  {
    id: 'megumin_explosion',
    name: 'Megumin',
    subtitle: 'Arch-Wizard of the Crimson Demons',
    anime: 'KonoSuba',
    rarity: 'SR',
    element: 'Flame',
    atk: 8200,
    def: 5500,
    hp: 15000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b89361-tq8PQQ4MmF0M.png',
    quote: 'Kurou yori mo kuroku... EKUSUPUROSHON!!',
    description: 'Penyihir Iblis Merah yang hanya mendedikasikan seluruh poin skillnya untuk satu-satunya sihir terhebat: Ledakan!',
    featured: false
  },
  {
    id: 'denji_chainsaw',
    name: 'Denji',
    subtitle: 'Chainsaw Devil Hybrid',
    anime: 'Chainsaw Man',
    rarity: 'SR',
    element: 'Blood',
    atk: 7700,
    def: 6800,
    hp: 17500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b130102-FO1VHNnEnLlB.png',
    quote: 'Kalau mimpi kalian mau menghalangiku makan roti selai, minggir sekarang juga!',
    description: 'Hibrida iblis gergaji mesin yang meregenerasi tubuhnya tanpa henti selama mendapatkan asupan darah segar.',
    featured: false
  },
  {
    id: 'alucard_hellsing',
    name: 'Alucard',
    subtitle: 'The Ultimate Vampire (Control Art: Level 0)',
    anime: 'Hellsing Ultimate',
    rarity: 'SR',
    element: 'Shadow',
    atk: 7800,
    def: 7100,
    hp: 17000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/n601-CVySkaFQgsPW.jpg',
    quote: 'Hanya manusia yang dapat membunuh monster seperti diriku.',
    description: 'Raja vampir legendaris bersenjata pistol kembar Casull & Jackal yang menampung jutaan jiwa korban dalam tubuhnya.',
    featured: false
  },

  // ===== 4. RARE (R) =====
  {
    id: 'nobara_kugisaki',
    name: 'Nobara Kugisaki',
    subtitle: 'Straw Doll Technique (Resonance)',
    anime: 'Jujutsu Kaisen',
    rarity: 'R',
    element: 'Blood',
    atk: 6700,
    def: 5900,
    hp: 14500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b133700-f6sOO3TcgLV6.png',
    quote: 'Kanzashi! Tomobari! Aku menyukai diriku yang cantik dan kuat!',
    description: 'Penyihir Jujutsu kelas 3 bersenjata palu, paku, dan boneka jerami yang menyerang inti jiwa lawan dari jarak jauh.',
    featured: false
  },
  {
    id: 'megumi_fushiguro',
    name: 'Megumi Fushiguro',
    subtitle: 'Ten Shadows Technique (Divine Dog)',
    anime: 'Jujutsu Kaisen',
    rarity: 'R',
    element: 'Shadow',
    atk: 6800,
    def: 6000,
    hp: 14800,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b126635-L0y3I92JSUkN.png',
    quote: 'Yatsuka no Tsurugi Ika Shinkou Gyuuma... MAHORAGA!',
    description: 'Pewaris teknik Sepuluh Bayangan klan Zenin yang mampu memanggil shikigami legendaris.',
    featured: false
  },
  {
    id: 'nanami_kento',
    name: 'Kento Nanami',
    subtitle: '7:3 Ratio Technique',
    anime: 'Jujutsu Kaisen',
    rarity: 'R',
    element: 'Steel',
    atk: 6900,
    def: 6100,
    hp: 15000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b133704-8wLTGjc234q2.png',
    quote: 'Kerja lembur adalah kejahatan. Mari kita selesaikan ini tepat waktu.',
    description: 'Mantan pialang saham yang menerapkan titik potong rasio 7:3 untuk menghasilkan tebasan kritikal mutlak.',
    featured: false
  },
  {
    id: 'anya_telepath',
    name: 'Anya Forger',
    subtitle: 'Esper Starlight (Waku Waku)',
    anime: 'Spy x Family',
    rarity: 'R',
    element: 'Mind',
    atk: 5800,
    def: 6600,
    hp: 14000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b138100-4Li0tWRCa5bQ.png',
    quote: 'Waku waku! Anya mau kacang dan menyelamatkan dunia bersama Papa & Mama!',
    description: 'Gadis esper cilik yang bisa membaca pikiran orang lain dan berusaha keras membantu misi perdamaian dunia ayahnya.',
    featured: false
  },
  {
    id: 'zenitsu_thunder',
    name: 'Zenitsu Agatsuma',
    subtitle: 'Thunderclap and Flash (Sixfold)',
    anime: 'Kimetsu no Yaiba',
    rarity: 'R',
    element: 'Lightning',
    atk: 6950,
    def: 5600,
    hp: 14200,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b129131-FZrQ7lSlxmEr.png',
    quote: 'Kaminari no Kokyuu, Ichi no Kata: Hekireki Issen! (Kilat Menggelegar!)',
    description: 'Pendekar penakut yang saat tertidur bertransformasi menjadi kilat berkecepatan dewa yang memenggal kepala iblis.',
    featured: false
  },
  {
    id: 'inosuke_beast',
    name: 'Inosuke Hashibira',
    subtitle: 'Beast Breathing (Lord of the Mountain)',
    anime: 'Kimetsu no Yaiba',
    rarity: 'R',
    element: 'Beast',
    atk: 6850,
    def: 5850,
    hp: 14600,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/n129130-SJC0Kn1DU39E.jpg',
    quote: 'Inoshishi Tosshin! Maju menyerang! Rajanya Gunung telah tiba!!',
    description: 'Pendekar bertopeng babi hutan pembelajar mandiri yang mengandalkan kepekaan indera peraba kulitnya.',
    featured: false
  },
  {
    id: 'bocchi_guitar',
    name: 'Hitori Gotoh (Bocchi)',
    subtitle: 'Guitar Hero & Social Anxiety Master',
    anime: 'Bocchi the Rock!',
    rarity: 'R',
    element: 'Sound',
    atk: 6600,
    def: 6200,
    hp: 14500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b257562-Ru35NYPfsqhY.png',
    quote: 'T-tolong jangan lihat aku... tapi dengarkan solo gitar Les Paul ini!',
    description: 'Gadis introvert pemalu yang bertransformasi menjadi dewa gitar rock berkecepatan jari menakjubkan.',
    featured: false
  },
  {
    id: 'marin_cosplay',
    name: 'Marin Kitagawa',
    subtitle: 'Cosplay Queen (Shizuku-tan)',
    anime: 'Sono Bisque Doll wa Koi wo Suru',
    rarity: 'R',
    element: 'Light',
    atk: 6500,
    def: 6300,
    hp: 14200,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b133676-kV2czE3C8Qls.png',
    quote: 'Gojo-kun, baju cosplay ini cocok banget di aku kan?!',
    description: 'Gadis SMA ceria pencinta anime dan game yang selalu totalitas mengekspresikan hobi cosplay-nya.',
    featured: false
  },
  {
    id: 'loid_forger',
    name: 'Loid Forger',
    subtitle: 'Master Spy (Twilight)',
    anime: 'Spy x Family',
    rarity: 'R',
    element: 'Secret',
    atk: 6700,
    def: 6100,
    hp: 14400,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b138101-7NCB0Md8zA6G.png',
    quote: 'Semua ini demi menjaga senyuman anak-anak di dunia yang damai.',
    description: 'Agen rahasia terbaik intelijen Westalis dengan seribu penyamaran dan perhitungan taktik tanpa cela.',
    featured: false
  },
  {
    id: 'spike_spiegel',
    name: 'Spike Spiegel',
    subtitle: 'Space Cowboy (Jeet Kune Do)',
    anime: 'Cowboy Bebop',
    rarity: 'R',
    element: 'Steel',
    atk: 6800,
    def: 5900,
    hp: 14300,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b1-ChxaldmieFlQ.png',
    quote: 'Whatever happens, happens... Bang.',
    description: 'Pemburu buronan luar angkasa bergaya santai yang menguasai seni bela diri Jeet Kune Do dan pilot handal.',
    featured: false
  },

  // ===== 5. COMMON (C) =====
  {
    id: 'yor_thorn',
    name: 'Yor Forger',
    subtitle: 'The Thorn Princess',
    anime: 'Spy x Family',
    rarity: 'C',
    element: 'Poison',
    atk: 5900,
    def: 4700,
    hp: 12000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b138102-ZOAu9jI2d5ke.png',
    quote: 'Bolehkah saya mengambil nyawa Anda malam hari ini?',
    description: 'Ibu rumah tangga anggun yang diam-diam merupakan pembunuh bayaran legendaris berkekuatan fisik manusia super.',
    featured: false
  },
  {
    id: 'kazuma_satou',
    name: 'Kazuma Satou',
    subtitle: 'The Scum Adventurer (Steal Master)',
    anime: 'KonoSuba',
    rarity: 'C',
    element: 'Luck',
    atk: 5200,
    def: 5100,
    hp: 11500,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b89364-7Th8Tv1XKJtt.png',
    quote: 'Hai, Kazuma desu. SUTEAAAALLL!!',
    description: 'Petualang isekai beruntung tinggi yang memimpin party paling kacau di dunia fantasi.',
    featured: false
  },
  {
    id: 'darkness_crusader',
    name: 'Darkness',
    subtitle: 'The Masochist Crusader',
    anime: 'KonoSuba',
    rarity: 'C',
    element: 'Holy',
    atk: 3200,
    def: 8900,
    hp: 16000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b89363-mm21Ll4NegUD.png',
    quote: 'Serang aku sekuat tenaga! Biarkan aku melindungi kalian semua!',
    description: 'Kesatria bangsawan dengan pertahanan fisik baja tak tertembus, meskipun serangannya jarang mengenai musuh.',
    featured: false
  },
  {
    id: 'king_opm',
    name: 'Genos',
    subtitle: 'Demon Cyborg (Incineration Cannon)',
    anime: 'One Punch Man',
    rarity: 'C',
    element: 'Flame',
    atk: 5800,
    def: 5200,
    hp: 13000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b73979-tVi9maPID881.jpg',
    quote: 'Sensei, tolong ajarkan aku cara menjadi kuat seperti Anda!',
    description: 'Cyborg pahlawan S-Class yang bertarung gigih menggunakan meriam pembakar berkekuatan ledakan tinggi.',
    featured: false
  },
  {
    id: 'aqua_goddess',
    name: 'Aqua',
    subtitle: 'Goddess of Water (Nature\'s Beauty)',
    anime: 'KonoSuba',
    rarity: 'C',
    element: 'Water',
    atk: 4200,
    def: 4200,
    hp: 10000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b89362-ibkc0eoECaW1.png',
    quote: 'KAZUMAAA! Tolongin aku, aku mau ditelan kodok raksasa lagi!!',
    description: 'Dewi air pemurni undead yang bertingkah manja dan sering mendatangkan bencana kocak bagi party-nya.',
    featured: false
  },
  {
    id: 'gintoki_sakata',
    name: 'Sakata Gintoki',
    subtitle: 'The White Yaksha (Odd Jobs Yorozuya)',
    anime: 'Gintama',
    rarity: 'C',
    element: 'Steel',
    atk: 6000,
    def: 5400,
    hp: 13000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/b672-cP5VPriN67xJ.png',
    quote: 'Daripada mikirin masa depan yang suram, mending kita beli parfait stroberi dulu.',
    description: 'Mantan samurai legendaris perang Joui yang kini menjalankan kantor serabutan Yorozuya dengan pedang kayunya.',
    featured: false
  },
  {
    id: 'speedwagon_chad',
    name: 'Robert E.O. Speedwagon',
    subtitle: 'The Ultimate Best Wingman & Narrator',
    anime: 'JoJo\'s Bizarre Adventure',
    rarity: 'C',
    element: 'Holy',
    atk: 3800,
    def: 8200,
    hp: 14000,
    image: 'https://s4.anilist.co/file/anilistcdn/character/large/n21938-7iTMOJ4i6ET8.png',
    quote: 'Bahkan Speedwagon pun merasa takjub melihat potensi luar biasa ini!',
    description: 'Pendiri Speedwagon Foundation yang selalu setia mendanai dan mendukung garis keturunan keluarga Joestar melintasi generasi.',
    featured: false
  }
];

export const getCardById = (id) => CARDS_DATABASE.find((c) => c.id === id) || null;

export const getCardsByRarity = (rarity) => CARDS_DATABASE.filter((c) => c.rarity === rarity);

// Hitung Total Combat Power (CP) dari satu kartu beserta star levelnya
export const calculateCardCP = (card, stars = 1) => {
  if (!card) return 0;
  const starMultiplier = 1 + (stars - 1) * 0.25; // +25% stat per bintang duplikat
  return Math.floor((card.atk * 1.5 + card.def * 1.2 + card.hp * 0.1) * starMultiplier);
};
